name: prize
description: Developed by MAlazhariy.
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  requests_inspector: ^4.2.3
  # Core
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  # Localization | flutter pub run easy_localization:generate -S ./assets/translations -f keys -O lib/core/utils/generated -o tr_locale_keys.g.dart
  easy_localization: ^3.0.7+1
  # Url launcher
  url_launcher: ^6.3.1
  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  # Internet connection
  internet_state_manager: ^1.8.0
  # Cache network images
  cached_network_image: ^3.4.1
  # Local storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  # Shimmer effect
  shimmer: ^3.0.0
  # Webview and HTML view (Html used for Privacy policy ...etc)
  webview_flutter: ^4.13.0
  flutter_widget_from_html: ^0.16.0
  # Firebase
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  # Carousel slider
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  # Image picker
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  # Image cropper to native crop & compress the image before upload
  image_cropper: ^9.1.0
  # Toast
  fluttertoast: ^8.2.12
  # Permission handler
  permission_handler: ^12.0.0+1
  # todo: Do you use Location
  geolocator: ^14.0.0
  # Time ago text previewer
  timeago: ^3.7.1
  # For animation
  flutter_animate: ^4.5.2
  # todo: PDF preview
  flutter_cached_pdfview: ^0.4.3
  # For app version
  package_info_plus: ^8.3.0
  # For Numbers conventions from Arabic to English and vice versa
  number_converter:
    path: packages/number_converter
  # For parsing data from APIs
  api_data_parser:
    path: packages/api_data_parser
  flutter_svg: ^2.1.0
  # For share
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  rename: ^3.1.0
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.3
  country_code_picker: ^3.3.0
  pinput: ^5.0.1
  chips_choice: ^3.0.1
  dotted_border: ^3.0.1
  freezed_annotation: ^3.1.0
  freezed: ^3.1.0 


  card_swiper: ^3.0.1
  photo_view: ^0.15.0
  syncfusion_flutter_sliders: ^30.1.39
  syncfusion_flutter_core: ^30.1.39
  timelines_plus: ^1.0.7

dependency_overrides:
  win32: ^5.13.0
  fwfh_webview: ^0.15.4
  webview_flutter_android: ^4.7.0
  source_gen: ^2.0.0
  wakelock_plus: ^1.3.2
  video_player_android: ^2.8.7
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  # For retrofit generation
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/
    - assets/fonts/poppins/
    - assets/fonts/ibm_plex_sans_arabic/
    - .env


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
    - family: IBM
      fonts:
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans_arabic/IBMPlexSansArabic-Thin.ttf
          weight: 100